import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/index.tsx"),
  route("authors", "routes/author/author.tsx"),
  route("authors/create", "routes/author/authorCreate.tsx"),
  route("authors/:id/edit", "routes/author/authorEdit.tsx"),
  route("authors/:id", "routes/author/authorDetail.tsx"),
  route("authors/:id/delete", "routes/author/authorDelete.tsx"),
  route("bookMasters", "routes/bookMaster/bookMaster.tsx"),
  route("bookMasters/create", "routes/bookMaster/bookMasterCreate.tsx"),
  route("bookMasters/:id/edit", "routes/bookMaster/bookMasterEdit.tsx"),
  route("bookMasters/:id", "routes/bookMaster/bookMasterDetail.tsx"),
  route("bookMasters/:id/delete", "routes/bookMaster/bookMasterDelete.tsx"),
  route("bookStockStatuses", "routes/bookStockStatus/bookStockStatus.tsx"),
  route("bookStockStatuses/create", "routes/bookStockStatus/bookStockStatusCreate.tsx"),
  route("bookStockStatuses/:id/edit", "routes/bookStockStatus/bookStockStatusEdit.tsx"),
  route("bookStockStatuses/:id", "routes/bookStockStatus/bookStockStatusDetail.tsx"),
  route("bookStocks", "routes/bookStock/bookStock.tsx"),
  route("bookStocks/create", "routes/bookStock/bookStockCreate.tsx"),
  route("bookStocks/:id/edit", "routes/bookStock/bookStockEdit.tsx"),
  route("bookStocks/:id", "routes/bookStock/bookStockDetail.tsx"),
  route("lendingStatuses", "routes/lendingStatus/lendingStatus.tsx"),
  route("lendingStatuses/create", "routes/lendingStatus/lendingStatusCreate.tsx"),
  route("lendingStatuses/:id/edit", "routes/lendingStatus/lendingStatusEdit.tsx"),
  route("lendingStatuses/:id", "routes/lendingStatus/lendingStatusDetail.tsx"),
  route("customers", "routes/customer/customer.tsx"),
  route("customers/create", "routes/customer/customerCreate.tsx"),
  route("customers/:id/edit", "routes/customer/customerEdit.tsx"),
  route("customers/:id", "routes/customer/customerDetail.tsx"),
  route("lendingSets", "routes/lendingSet/lendingSet.tsx"),
  route("lendingSets/create", "routes/lendingSet/lendingSetCreate.tsx"),
  route("lendingSets/:id/edit", "routes/lendingSet/lendingSetEdit.tsx"),
  route("lendingSets/:id", "routes/lendingSet/lendingSetDetail.tsx"),
] satisfies RouteConfig;
