import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/index.tsx"),
  route("authors", "routes/author/author.tsx"),
  route("authors/create", "routes/author/authorCreate.tsx"),
  route("authors/:id/edit", "routes/author/authorEdit.tsx"),
  route("authors/:id", "routes/author/authorDetail.tsx"),
  route("bookMasters", "routes/bookMaster/bookMaster.tsx"),
  route("bookMasters/create", "routes/bookMaster/bookMasterCreate.tsx"),
  route("bookMasters/:id/edit", "routes/bookMaster/bookMasterEdit.tsx"),
  route("bookMasters/:id", "routes/bookMaster/bookMasterDetail.tsx"),
  route("bookStockStatuses", "routes/bookStockStatus/bookStockStatus.tsx"),
  route("bookStockStatuses/create", "routes/bookStockStatus/bookStockStatusCreate.tsx"),
  route("bookStockStatuses/:id/edit", "routes/bookStockStatus/bookStockStatusEdit.tsx"),
  route("bookStockStatuses/:id", "routes/bookStockStatus/bookStockStatusDetail.tsx"),
  route("bookStocks", "routes/bookStock/bookStock.tsx"),
  route("bookStocks/create", "routes/bookStock/bookStockCreate.tsx"),
  route("bookStocks/:id/edit", "routes/bookStock/bookStockEdit.tsx"),
  route("bookStocks/:id", "routes/bookStock/bookStockDetail.tsx"),
  route("lendingStatuses", "routes/lendingStatus/lendingStatus.tsx"),
  route("lendingStatuses/create", "routes/lendingStatus/lendingStatusCreate.tsx"),
  route("lendingStatuses/:id/edit", "routes/lendingStatus/lendingStatusEdit.tsx"),
  route("lendingStatuses/:id", "routes/lendingStatus/lendingStatusDetail.tsx"),
] satisfies RouteConfig;
